name: Temporal test

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ChiPass repository
        run: |
          git clone https://codeberg.org/ChiPass/ChiPass.git .

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache cmake ninja-build \
            qt6-base-dev qt6-base-private-dev qt6-svg-dev qt6-tools-dev qt6-5compat-dev libreadline-dev \
            libbotan-2-dev libargon2-dev libminizip-dev zlib1g-dev libqrencode-dev libpcsclite-dev libusb-1.0-0-dev \
            xvfb xclip libxi-dev libxtst-dev \
            asciidoctor

      - name: Set up caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ChiPass-${{ hashFiles('cmake/**', 'src/**', 'CMakeLists.txt') }}
          restore-keys: |
            ChiPass-${{ hashFiles('cmake/**', 'src/**', 'CMakeLists.txt') }}
            ChiPass-

      - name: Set up ccache
        run: |
          ccache --max-size=3G -z

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DWITH_CCACHE=ON \
            -DWITH_XC_ALL=ON \
            -DWITH_GUI_TESTS=OFF

      - name: Build
        run: |
          cmake --build build

      - name: Print ccache statistics
        run: |
          ccache -s

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: chipass-linux
          path: build/
